### ISSUE TITLE
Preferences not saved

### ISSUE THREAD

**Issue by syrm** [flathub/com.albiononline.AlbionOnline#13]
Hello,

Thank you for your work.
When i change the preferences in game and reload my settings are lost.

**Comment by valentindavid** [comment]
Could you be more precise? Which settings are lost?

I have tried to change volume, and game tag size for example. It was properly saved and reloaded.

**Comment by syrm** [comment]
Resolution and full screen or window mode

**Comment by valentindavid** [comment]
I am not sure this is due to flatpak. Probably Albion Online behavior. I have noticed that fullscreen would ignore resolution and take the current resolution of the screen. I think it never start fullscreen because there are bugs with Unity3d about starting in fullscreen. And that change was done recently. It was not like that before release, even with flatpak. I may be wrong. Have you seen a different behavior when not using flatpak?

**Comment by syrm** [comment]
Without flatpak i can't run Albion so i can't test, but on windows everything is fine

**Comment by valentindavid** [comment]
OK. I am closing the ticket. If anyone ever see it working on Linux without using flatpak, then reopen.

Thanks for reporting though.
